django_app_1/django_app_1/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('menu/', include('menu.urls'))
]

django_app_1/menu/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.menu)
]

django_app_1/menu/models.py
from django.db import models


class Menu(models.Model):
    '''Храним имена и уникальные идентификаторы меню.'''

    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True)


class MenuItem(models.Model):
    '''Храним сами модели.
    Каждое меню может быть подменю другого меню, поэтому
    есть ссылка на родительское меню.
    Сущности будут ссылаться на другие сущности в таблице.
    По принципу многие к одному??
    Дочерние меню могут ссылаться все на одно родительское.'''

    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        'MenuItem',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    url = models.CharField(max_length=200, blank=True)
    named_url = models.CharField(max_length=100, blank=True)
    order = models.PositiveIntegerField(default=0)

django_app_1/django_app_1/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse('Привет мир!')

django_app_1/menu/views.py
from django.shortcuts import render


def menu(request):
    template_name = 'menu/menu_template.html'
    return render(request, template_name=template_name)

django_app_1/menu/templates/menu/menu_template.html
{% load menu_tag %}
{% draw_menu 'main_menu' as menu %}


<ul>
  {% for item in menu.menuitem_set.all %}
    {% if not item.parent %}
      <li class="{% if item.url == request.path %}active{% endif %}">
        <a href="{{ item.url }}">{{ item.title }}</a>
        {% if item.children.exists %}
          <ul>
            {% for child in item.children.all %}
              <li class="{% if child.url == request.path %}active{% endif %}">
                {{ child.title }}
              </li>
            {% endfor %}
          </ul>
        {% endif %}
      </li>
    {% endif %}
  {% endfor %}
</ul>